version: '3.3'

services:
  m5paper-server:
    build: .  # Build the image from the Dockerfile in this directory
    image: m5paper-server-image
    container_name: m5paper-server
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8765:8765"
    environment:
      - SERVER_IP=192.168.1.55
      - TELEGRAM_TOKEN=YOUR_REAL_TOKEN_HERE
    volumes:
      - ./settings.json:/settings.json
      - ./friends.json:/friends.json